export interface Document {

  /* UM DOS PRINCIPIOS DO PATRÃO BRIDGE É A DISSOCIAÇÃO DA IMPLEMENTAÇÃO COM A CLASSE CONCRETA, DESSA FORMA É CRIADA A CLASSE DOCUMENT
    A FIM DE VINCULAR ELA DOIS TIPOS DE DOCUMENTO, CNPJ E CPF, SENDO OS MESMO IMPLEMENTADOS DENTRO NO DIRETORIO SRC/IMPLEMENTATION/DOCUMENT
  */

  showDocument(document: string): string;

}
